package javaapplication4;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.text.*; 
import java.awt.print.*;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sahira Mehta
 */
public class Edit extends javax.swing.JFrame {
Connection con;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form Search
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        import1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dte1 = new com.toedter.calendar.JDateChooser();
        dte2 = new com.toedter.calendar.JDateChooser();
        product = new javax.swing.JTextField();
        csno = new javax.swing.JTextField();
        byer = new javax.swing.JTextField();
        sellernme = new javax.swing.JTextField();
        quty = new javax.swing.JTextField();
        prce = new javax.swing.JTextField();
        trms = new javax.swing.JTextField();
        offprce = new javax.swing.JTextField();
        co = new javax.swing.JTextField();
        rmrks = new javax.swing.JScrollPane();
        rmks1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        print = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(922, 633));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        import1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date_of_enqy", "Reply_on_enqy", "Product_Name", "Cas_No", "Buyer_Name", "Seller_Plant", "Quantity", "Price ", "Terms", "Offered_Price", "COA", "Remarks"
            }
        ));
        import1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                import1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(import1);

        jLabel1.setText("DATE OF ENQUIRY");

        jLabel2.setText("REPLY ON ENQUIRY");

        jLabel12.setText("PRODUCT NAME");

        jLabel14.setText("Cas no");

        jLabel4.setText("Buyer Name");

        jLabel5.setText("SELLER/PLANT NAME");

        jLabel6.setText("QUANTITY");

        jLabel7.setText("price /KG");

        jLabel8.setText("Terms");

        jLabel9.setText("Offered Price");

        jLabel10.setText("COA");

        jLabel11.setText("Remarks");

        rmks1.setColumns(20);
        rmks1.setRows(5);
        rmrks.setViewportView(rmks1);

        delete.setText("Delete");

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        print.setText("print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(delete)
                .addGap(18, 18, 18)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(save)
                    .addComponent(print)
                    .addComponent(exit))
                .addContainerGap())
        );

        chk1.setText("IMPORT");
        chk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk1ActionPerformed(evt);
            }
        });

        chk2.setText("EXPORT");
        chk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2ActionPerformed(evt);
            }
        });

        jButton2.setText("open");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(chk1)
                                .addGap(58, 58, 58)
                                .addComponent(chk2)
                                .addGap(102, 102, 102)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                                .addComponent(dte1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(byer)
                                                    .addComponent(trms, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(offprce))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(sellernme))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dte2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(quty)
                                                    .addComponent(co, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(csno)
                                            .addComponent(prce, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rmrks, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chk1)
                        .addComponent(chk2)
                        .addComponent(jButton2))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(dte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(byer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellernme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(trms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(offprce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(co, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rmrks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void chk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk1ActionPerformed
String query123="select * from import_data";
    try {
   DefaultTableModel model = (DefaultTableModel) import1.getModel();
while(model.getRowCount()>0){
for(int i = 0;i<model.getRowCount();i++){model.removeRow(i);}}
con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sumsahi_data","root","root");
pst= (PreparedStatement) con.createStatement();
rs= pst.executeQuery(query123);
int count=0;
while(rs.next()){
count++;
String Date_of_enqy= rs.getString("date_of_enqy");
String Reply_on_enqy  = rs.getString("rply_of_enqy");
String Product_Name= rs.getString("product_nme");
String Cas_No = rs.getString("casno");
String Buyer_Name = rs.getString("buyer_nme");
String Seller_Plant = rs.getString("seller_plant");
String Quantity= rs.getString("qty");
String Price= rs.getString("price");
String Terms= rs.getString("terms");
String Offered_Price= rs.getString("offered_price");
String COA = rs.getString("coa");
String Remarks= rs.getString("remarks");

 Object[] row1 = {Date_of_enqy,Reply_on_enqy,Product_Name,Cas_No,Buyer_Name,Seller_Plant,Quantity,Price,Terms,Offered_Price,COA,Remarks};
 model.addRow(row1);
}
System.out.println(count);

        pst.close();
        con.close();
        }
     catch (SQLException ex) {
       System.out.println(ex);
    }
    }//GEN-LAST:event_chk1ActionPerformed

    private void chk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2ActionPerformed
String query1234="select * from export_data";
    try {
   DefaultTableModel model = (DefaultTableModel) import1.getModel();
while(model.getRowCount()>0){
for(int i = 0;i<model.getRowCount();i++){model.removeRow(i);}}
 con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sumsahi_data","root","root");
pst= (PreparedStatement) con.createStatement();
rs= pst.executeQuery(query1234);
int count=0;
while(rs.next()){
count++;
String Date_of_enqy= rs.getString("date_of_enqy");
String Reply_on_enqy  = rs.getString("rply_of_enqy");
String Product_Name= rs.getString("product_nme");
String Cas_No = rs.getString("casno");
String Buyer_Name = rs.getString("buyer_nme");
String Seller_Plant = rs.getString("seller_plant");
String Quantity= rs.getString("qty");
String Price= rs.getString("price");
String Terms= rs.getString("terms");
String Offered_Price= rs.getString("offered_price");
String COA = rs.getString("coa");
String Remarks= rs.getString("remarks");

 Object[] row1 = {Date_of_enqy,Reply_on_enqy,Product_Name,Cas_No,Buyer_Name,Seller_Plant,Quantity,Price,Terms,Offered_Price,COA,Remarks};
 model.addRow(row1);
}
System.out.println(count);

        pst.close();
        con.close();
        }
     catch (SQLException ex) {
       System.out.println(ex);
    }
    }//GEN-LAST:event_chk2ActionPerformed

    private void import1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_import1MouseClicked
 if(chk1.isSelected()){
    try{
       
java.sql.Date date = new java.sql.Date(dte1.getDate().getTime());
java.sql.Date date1 = new java.sql.Date(dte2.getDate().getTime());
String value1= product.getText();
String value2 = csno.getText();
String value3 = byer.getText();
String value4 = sellernme.getText();
String value5 = quty.getText();
String value6 = prce.getText();
String value7 = trms.getText();
String value8 = offprce.getText();
String value9 = co.getText();
String value10 = rmks1.getText();
 con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sumsahi_data","root","root");
String sqlqry = "UPDATE import_data set date_of_enqy='"+date+"' ,rply_of_enqy='"+date1+"' ,product_nme='"+value1+"' ,casno='"+value2+"' ,buyer_nme='"+value3+"' ,seller_plant='"+value4+"' ,qty='"+value5+"' ,price='"+value6+"' ,terms='"+value7+"' ,offered_price='"+value8+"' ,coa='"+value9+"' ,remarks='"+value10+"'";
   pst =con.prepareStatement(sqlqry);
    pst.execute();
    JOptionPane.showMessageDialog(null,"Sucessfully Updated");
    }     catch (Exception ex) {
       System.out.println(ex);
    } 
    Update_Table();}
if(chk2.isSelected()){    
    try{
java.sql.Date date = new java.sql.Date(dte1.getDate().getTime());
java.sql.Date date1 = new java.sql.Date(dte2.getDate().getTime());
String value1= product.getText();
String value2 = csno.getText();
String value3 = byer.getText();
String value4 = sellernme.getText();
String value5 = quty.getText();
String value6 = prce.getText();
String value7 = trms.getText();
String value8 = offprce.getText();
String value9 = co.getText();
String value10 = rmks1.getText();
}     catch (Exception ex) {
       System.out.println(ex);
    }Update_Table();}
    }//GEN-LAST:event_import1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (chk1.isSelected()){
    String query123="select * from import_data";
    try {
   DefaultTableModel model = (DefaultTableModel) import1.getModel();
while(model.getRowCount()>0){
for(int i = 0;i<model.getRowCount();i++){model.removeRow(i);}}
con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sumsahi_data","root","root");
pst= (PreparedStatement) con.createStatement();
rs= pst.executeQuery(query123);
int count=0;
while(rs.next()){
count++;
String Date_of_enqy= rs.getString("date_of_enqy");
String Reply_on_enqy  = rs.getString("rply_of_enqy");
String Product_Name= rs.getString("product_nme");
String Cas_No = rs.getString("casno");
String Buyer_Name = rs.getString("buyer_nme");
String Seller_Plant = rs.getString("seller_plant");
String Quantity= rs.getString("qty");
String Price= rs.getString("price");
String Terms= rs.getString("terms");
String Offered_Price= rs.getString("offered_price");
String COA = rs.getString("coa");
String Remarks= rs.getString("remarks");

 Object[] row1 = {Date_of_enqy,Reply_on_enqy,Product_Name,Cas_No,Buyer_Name,Seller_Plant,Quantity,Price,Terms,Offered_Price,COA,Remarks};
 model.addRow(row1);
}
System.out.println(count);

        pst.close();
        con.close();
        }
     catch (SQLException ex) {
       System.out.println(ex);
    }}
    if(chk2.isSelected()){
    String query1234="select * from export_data";
    try {
   DefaultTableModel model = (DefaultTableModel) import1.getModel();
while(model.getRowCount()>0){
for(int i = 0;i<model.getRowCount();i++){model.removeRow(i);}}
 con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sumsahi_data","root","root");
pst= (PreparedStatement) con.createStatement();
rs= pst.executeQuery(query1234);
int count=0;
while(rs.next()){
count++;
String Date_of_enqy= rs.getString("date_of_enqy");
String Reply_on_enqy  = rs.getString("rply_of_enqy");
String Product_Name= rs.getString("product_nme");
String Cas_No = rs.getString("casno");
String Buyer_Name = rs.getString("buyer_nme");
String Seller_Plant = rs.getString("seller_plant");
String Quantity= rs.getString("qty");
String Price= rs.getString("price");
String Terms= rs.getString("terms");
String Offered_Price= rs.getString("offered_price");
String COA = rs.getString("coa");
String Remarks= rs.getString("remarks");

 Object[] row1 = {Date_of_enqy,Reply_on_enqy,Product_Name,Cas_No,Buyer_Name,Seller_Plant,Quantity,Price,Terms,Offered_Price,COA,Remarks};
 model.addRow(row1);
}
System.out.println(count);

        pst.close();
        con.close();
        }
     catch (SQLException ex) {
       System.out.println(ex);
    }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
MessageFormat header= new MessageFormat("report Print");
MessageFormat footer= new MessageFormat("page(0,number,Integer)");
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField byer;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JTextField co;
    private javax.swing.JTextField csno;
    private javax.swing.JButton delete;
    private com.toedter.calendar.JDateChooser dte1;
    private com.toedter.calendar.JDateChooser dte2;
    private javax.swing.JButton exit;
    public javax.swing.JTable import1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField offprce;
    private javax.swing.JTextField prce;
    private javax.swing.JButton print;
    private javax.swing.JTextField product;
    private javax.swing.JTextField quty;
    private javax.swing.JTextArea rmks1;
    private javax.swing.JScrollPane rmrks;
    private javax.swing.JButton save;
    private javax.swing.JTextField sellernme;
    private javax.swing.JTextField trms;
    // End of variables declaration//GEN-END:variables

    private void update_Table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void Update_Table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
