/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sahira Mehta
 */
public class Edit extends javax.swing.JFrame {
Connection con;

ResultSet rs;
Statement pst;

    /**
     * Creates new form Search
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        import1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dte1 = new com.toedter.calendar.JDateChooser();
        dte2 = new com.toedter.calendar.JDateChooser();
        product = new javax.swing.JTextField();
        csno = new javax.swing.JTextField();
        byer = new javax.swing.JTextField();
        sellernme = new javax.swing.JTextField();
        quty = new javax.swing.JTextField();
        prce = new javax.swing.JTextField();
        trms = new javax.swing.JTextField();
        offprce = new javax.swing.JTextField();
        co = new javax.swing.JTextField();
        rmrks = new javax.swing.JScrollPane();
        rmks1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        print = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(922, 633));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        import1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date_of_enqy", "Reply_on_enqy", "Product_Name", "Cas_No", "Buyer_Name", "Seller_Plant", "Quantity", "Price ", "Terms", "Offered_Price", "COA", "Remarks"
            }
        ));
        import1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                import1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(import1);

        jLabel1.setText("DATE OF ENQUIRY");

        jLabel2.setText("REPLY ON ENQUIRY");

        jLabel12.setText("PRODUCT NAME");

        jLabel14.setText("Cas no");

        jLabel4.setText("Buyer Name");

        jLabel5.setText("SELLER/PLANT NAME");

        jLabel6.setText("QUANTITY");

        jLabel7.setText("price /KG");

        jLabel8.setText("Terms");

        jLabel9.setText("Offered Price");

        jLabel10.setText("COA");

        jLabel11.setText("Remarks");

        dte1.setDateFormatString("yyyy-MM-dd\n");

        dte2.setDateFormatString("yyyy-MM-dd");

        rmks1.setColumns(20);
        rmks1.setRows(5);
        rmrks.setViewportView(rmks1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete.setText("Delete");
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 11, 73, -1));

        print.setText("print");
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 11, 79, -1));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 11, -1, -1));

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        chk1.setText("IMPORT");
        chk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk1ActionPerformed(evt);
            }
        });

        chk2.setText("EXPORT");
        chk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2ActionPerformed(evt);
            }
        });

        jButton2.setText("open");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(chk1)
                                .addGap(58, 58, 58)
                                .addComponent(chk2)
                                .addGap(95, 95, 95)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dte1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(byer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(trms, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(offprce)
                                    .addComponent(sellernme)
                                    .addComponent(dte2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(product)
                                    .addComponent(quty, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(co))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prce)
                                    .addComponent(rmrks)
                                    .addComponent(csno))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chk1)
                        .addComponent(chk2)
                        .addComponent(jButton2))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(dte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14))
                    .addComponent(csno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(byer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellernme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rmrks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(trms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(offprce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(co, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
if(chk1.isSelected()){
    try{
Class.forName("java.sql.Driver");  // MySQL database connection
con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sumsahi_data?zeroDateTimeBehavior=convertToNull","root","admin");
PreparedStatement pst1= con.prepareStatement("INSERT INTO import_data(date_of_enqy,rply_of_enqy,product_nme,casno,buyer_nme,seller_plant,qty,price,terms,offered_price,coa,remarks) values(?,?,?,?,?,?,?,?,?,?,?,?);");
pst1.setString(1, ((JTextField)dte2.getDateEditor().getUiComponent()).getText());
pst1.setString(2, ((JTextField)dte1.getDateEditor().getUiComponent()).getText());
pst1.setString(3, product.getText());
pst1.setString(4, csno.getText());
pst1.setString(5, byer.getText());
pst1.setString(6, sellernme.getText());
pst1.setString(7, quty.getText());
pst1.setString(8, prce.getText());
pst1.setString(9, trms.getText());
pst1.setString(10, offprce.getText());
pst1.setString(11, co.getText());
pst1.setString(12, rmks1.getText());
pst1.execute();
JOptionPane.showMessageDialog(null,"sucess - Data saved");
}
catch(Exception e){System.out.println(e);}
}
if (chk2.isSelected()){
try{
Class.forName("java.sql.Driver");  // MySQL database connection
con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sumsahi_data?zeroDateTimeBehavior=convertToNull","root","admin");
PreparedStatement pst1= con.prepareStatement("INSERT INTO export_data(date_of_enqy,rply_of_enqy,product_nme,casno,buyer_nme,seller_plant,qty,price,terms,offered_price,coa,remarks) values(?,?,?,?,?,?,?,?,?,?,?,?);");
pst1.setString(1, ((JTextField)dte2.getDateEditor().getUiComponent()).getText());
pst1.setString(2, ((JTextField)dte1.getDateEditor().getUiComponent()).getText());
pst1.setString(3, product.getText());
pst1.setString(4, csno.getText());
pst1.setString(5, byer.getText());
pst1.setString(6, sellernme.getText());
pst1.setString(7, quty.getText());
pst1.setString(8, prce.getText());
pst1.setString(9, trms.getText());
pst1.setString(10, offprce.getText());
pst1.setString(11, co.getText());
pst1.setString(12, rmks1.getText());
pst1.execute();
JOptionPane.showMessageDialog(null,"sucess - Data saved");
}
catch(Exception e){System.out.println(e);}
}
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void chk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk1ActionPerformed

    }//GEN-LAST:event_chk1ActionPerformed

    private void chk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2ActionPerformed

    }//GEN-LAST:event_chk2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String query123="select * from import_data;";
String query1234="select * from export_data;";
if (chk1.isSelected()){
    try {
   DefaultTableModel model = (DefaultTableModel) import1.getModel();
while(model.getRowCount()>0){
for(int i = 0;i<model.getRowCount();i++){model.removeRow(i);}
}
con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sumsahi_data","root","admin");
pst= con.createStatement();
rs= pst.executeQuery(query123);
int count=0;
while(rs.next()){
count++;
String Date_of_enqy= rs.getString("date_of_enqy");
String Reply_on_enqy  = rs.getString("rply_of_enqy");
String Product_Name= rs.getString("product_nme");
String Cas_No = rs.getString("casno");
String Buyer_Name = rs.getString("buyer_nme");
String Seller_Plant = rs.getString("seller_plant");
String Quantity= rs.getString("qty");
String Price= rs.getString("price");
String Terms= rs.getString("terms");
String Offered_Price= rs.getString("offered_price");
String COA = rs.getString("coa");
String Remarks= rs.getString("remarks");

 Object[] row1 = {Date_of_enqy,Reply_on_enqy,Product_Name,Cas_No,Buyer_Name,Seller_Plant,Quantity,Price,Terms,Offered_Price,COA,Remarks};
 model.addRow(row1);
}
System.out.println(count);

        }
     catch (SQLException ex) {
       System.out.println(ex);
    }}
if (chk2.isSelected()){
    try {
   DefaultTableModel model = (DefaultTableModel) import1.getModel();
while(model.getRowCount()>0){
for(int i = 0;i<model.getRowCount();i++){model.removeRow(i);}
}
con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sumsahi_data","root","admin");
pst= con.createStatement();
rs= pst.executeQuery(query1234);
int count=0;
while(rs.next()){
count++;
String Date_of_enqy= rs.getString("date_of_enqy");
String Reply_on_enqy  = rs.getString("rply_of_enqy");
String Product_Name= rs.getString("product_nme");
String Cas_No = rs.getString("casno");
String Buyer_Name = rs.getString("buyer_nme");
String Seller_Plant = rs.getString("seller_plant");
String Quantity= rs.getString("qty");
String Price= rs.getString("price");
String Terms= rs.getString("terms");
String Offered_Price= rs.getString("offered_price");
String COA = rs.getString("coa");
String Remarks= rs.getString("remarks");

 Object[] row1 = {Date_of_enqy,Reply_on_enqy,Product_Name,Cas_No,Buyer_Name,Seller_Plant,Quantity,Price,Terms,Offered_Price,COA,Remarks};
 model.addRow(row1);
}
System.out.println(count);

        }
     catch (SQLException ex) {
       System.out.println(ex);
    }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void import1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_import1MouseClicked
if(chk1.isSelected()){
try{
int row= import1.getSelectedRow();
String tbl_click=(import1.getModel().getValueAt(row,2).toString());
String sql="select * from import_data where product_nme='"+tbl_click+"';";
pst= con.createStatement();
rs= pst.executeQuery(sql);
if(rs.next()){
Date v1= rs.getDate("date_of_enqy");
dte2.setDate(v1);
Date v2= rs.getDate("rply_of_enqy");
dte1.setDate(v2);
String v3= rs.getString("product_nme");
product.setText(v3);
String v4= rs.getString("casno");
csno.setText(v4);
String v5= rs.getString("buyer_nme");
byer.setText(v5);
String v6 = rs.getString("seller_plant");
sellernme.setText(v6);
String v7 = rs.getString("qty");
quty.setText(v7);
String v8= rs.getString("price");
prce.setText(v8);
String v9=rs.getString("terms");
trms.setText("v9");
String v10 = rs.getString("offered_price");
offprce.setText(v10);
String v11 = rs.getString("coa");
co.setText(v11);
String v12 = rs.getString("remarks");
rmks1.setText(v12);
}
}
catch(Exception e){
System.out.println(e);}
}
if(chk2.isSelected()){
try{
int row= import1.getSelectedRow();
String tbl_click=(import1.getModel().getValueAt(row,2).toString());
String sql="select * from export_data where product_nme='"+tbl_click+"';";
pst= con.createStatement();
rs= pst.executeQuery(sql);
if(rs.next()){
Date v1= rs.getDate("date_of_enqy");
dte2.setDate(v1);
Date v2= rs.getDate("rply_of_enqy");
dte1.setDate(v2);
String v3= rs.getString("product_nme");
product.setText(v3);
String v4= rs.getString("casno");
csno.setText(v4);
String v5= rs.getString("buyer_nme");
byer.setText(v5);
String v6 = rs.getString("seller_plant");
sellernme.setText(v6);
String v7 = rs.getString("qty");
quty.setText(v7);
String v8= rs.getString("price");
prce.setText(v8);
String v9=rs.getString("terms");
trms.setText("v9");
String v10 = rs.getString("offered_price");
offprce.setText(v10);
String v11 = rs.getString("coa");
co.setText(v11);
String v12 = rs.getString("remarks");
rmks1.setText(v12);
}
}
catch(Exception e){
System.out.println(e);}
}
    }//GEN-LAST:event_import1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if(chk1.isSelected())
    try{
java.util.Date v1=  dte2.getDate();
java.util.Date v2= (Date) dte1.getDate();
String v3= product.getText();
String v4= csno.getText();
String v5= byer.getText();
String v6= sellernme.getText();
String v7= quty.getText();
String v8= prce.getText();
String v9= trms.getText();
String v10= co.getText();
String v11= offprce.getText();
String v12= rmks1.getText();   
String sql="UPDATE import_data set date_of_enqy='"+v1+"' ,rply_of_enqy='"+v2+"' ,product_nme='"+v3+"' ,casno='"+v4+"' ,buyer_nme='"+v5+"' ,seller_plant='"+v6+"' ,qty='"+v7+"' ,price='"+v8+"' ,terms='"+v9+" ,offered_price='"+v10+"' ,coa='"+v11+"' ,remarks='"+v12+"';";
PreparedStatement pst1= con.prepareStatement(sql);
    pst1.execute();
    JOptionPane.showMessageDialog(null, "Updated");
    }
catch(Exception e){
System.out.println(e);
}
if(chk2.isSelected()){
    try{

}
catch(Exception e){
System.out.println(e);
}    
    }
    }//GEN-LAST:event_jButton4ActionPerformed

       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField byer;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JTextField co;
    private javax.swing.JTextField csno;
    private javax.swing.JButton delete;
    private com.toedter.calendar.JDateChooser dte1;
    private com.toedter.calendar.JDateChooser dte2;
    private javax.swing.JButton exit;
    public javax.swing.JTable import1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField offprce;
    private javax.swing.JTextField prce;
    private javax.swing.JButton print;
    private javax.swing.JTextField product;
    private javax.swing.JTextField quty;
    private javax.swing.JTextArea rmks1;
    private javax.swing.JScrollPane rmrks;
    private javax.swing.JButton save;
    private javax.swing.JTextField sellernme;
    private javax.swing.JTextField trms;
    // End of variables declaration//GEN-END:variables

    private void update_Table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void Update_Table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void date1(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void date(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
