/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.print.PrinterException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.*;
import java.awt.print.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.*;
/**
 *
 * @author Sahira Mehta
 */
public class Main extends javax.swing.JFrame {
Connection con;
Statement pst;
ResultSet rs;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Import2 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        import1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Export2 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        export1 = new javax.swing.JTable();
        btn = new javax.swing.JButton();
        imp = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        Import2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Import2.setMinimumSize(new java.awt.Dimension(1050, 550));

        import1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date_of_enqy", "Reply_on_enqy", "Product_Name", "Cas_No", "Buyer_Name", "Seller_Plant", "Quantity", "Price ", "Terms", "Offered_Price", "COA", "Remarks"
            }
        ));
        jScrollPane1.setViewportView(import1);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Print table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Import2Layout = new javax.swing.GroupLayout(Import2.getContentPane());
        Import2.getContentPane().setLayout(Import2Layout);
        Import2Layout.setHorizontalGroup(
            Import2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Import2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Import2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Import2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Import2Layout.setVerticalGroup(
            Import2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Import2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Import2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Export2.setMinimumSize(new java.awt.Dimension(1050, 550));

        export1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date_of_enqy", "Reply_on_enqy", "Product_Name", "Cas_No", "Buyer_Name", "Seller_Plant", "Quantity", "Price ", "Terms", "Offered_Price", "COA", "Remarks"
            }
        ));
        jScrollPane2.setViewportView(export1);

        btn.setText("Back");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Export2Layout = new javax.swing.GroupLayout(Export2.getContentPane());
        Export2.getContentPane().setLayout(Export2Layout);
        Export2Layout.setHorizontalGroup(
            Export2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Export2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(Export2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Export2Layout.setVerticalGroup(
            Export2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Export2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imp.setText("From Import");
        imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impActionPerformed(evt);
            }
        });

        exp.setText("From Export");
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imp)
                            .addComponent(exp)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(56, 56, 56)
                .addComponent(imp)
                .addGap(37, 37, 37)
                .addComponent(exp)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void impActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impActionPerformed
Import2.setVisible(true);
String query123="select * from import_data";
    try {
   DefaultTableModel model = (DefaultTableModel) import1.getModel();
while(model.getRowCount()>0){
for(int i = 0;i<model.getRowCount();i++){model.removeRow(i);}}

con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sumsahi_data","root","admin");
pst= con.createStatement();
rs= pst.executeQuery(query123);
int count=0;
while(rs.next()){
count++;
String Date_of_enqy= rs.getString("date_of_enqy");
String Reply_on_enqy  = rs.getString("rply_of_enqy");
String Product_Name= rs.getString("product_nme");
String Cas_No = rs.getString("casno");
String Buyer_Name = rs.getString("buyer_nme");
String Seller_Plant = rs.getString("seller_plant");
String Quantity= rs.getString("qty");
String Price= rs.getString("price");
String Terms= rs.getString("terms");
String Offered_Price= rs.getString("offered_price");
String COA = rs.getString("coa");
String Remarks= rs.getString("remarks");

 Object[] row1 = {Date_of_enqy,Reply_on_enqy,Product_Name,Cas_No,Buyer_Name,Seller_Plant,Quantity,Price,Terms,Offered_Price,COA,Remarks};
 model.addRow(row1);
}
System.out.println(count);

        pst.close();
        con.close();
        
    }
     catch (SQLException ex) {
       System.out.println(ex);
    }
    }//GEN-LAST:event_impActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
Export2.setVisible(true);
String query12="select * from export_data";

    try {
        DefaultTableModel model = (DefaultTableModel) export1.getModel();
while(model.getRowCount()>0){
for(int i = 0;i<model.getRowCount();i++){model.removeRow(i);}}
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sumsahi_data","root","admin");
pst= con.createStatement();
rs= pst.executeQuery(query12);
int count=0;
while(rs.next()){
count++;
String Date_of_enqy= rs.getString("date_of_enqy");
String Reply_on_enqy  = rs.getString("rply_of_enqy");
String Product_Name= rs.getString("product_nme");
String Cas_No = rs.getString("casno");
String Buyer_Name = rs.getString("buyer_nme");
String Seller_Plant = rs.getString("seller_plant");
String Quantity= rs.getString("qty");
String Price= rs.getString("price");
String Terms= rs.getString("terms");
String Offered_Price= rs.getString("offered_price");
String COA = rs.getString("coa");
String Remarks= rs.getString("remarks");

 Object[] row1 = {Date_of_enqy,Reply_on_enqy,Product_Name,Cas_No,Buyer_Name,Seller_Plant,Quantity,Price,Terms,Offered_Price,COA,Remarks};
 model.addRow(row1);
}
System.out.println(count);

        pst.close();
        con.close();
        
    }
     catch (SQLException ex) {
       System.out.println(ex);
    }
    }//GEN-LAST:event_expActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Import2.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
Export2.setVisible(false);
    }//GEN-LAST:event_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
MessageFormat header= new MessageFormat("Sumsahi Import list");
MessageFormat footer= new MessageFormat("page(0,number,Integer)");
    try {
        import1.print(JTable.PrintMode.NORMAL,header,footer);
    } catch (PrinterException ex) {
       System.out.println(ex);
    }  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Export2;
    private javax.swing.JFrame Import2;
    private javax.swing.JButton btn;
    private javax.swing.JButton exp;
    private javax.swing.JTable export1;
    private javax.swing.JButton imp;
    private javax.swing.JTable import1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
